config/routes.rb
Rails.application.routes.draw do

  root 'topics#index'

  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  resources :users, only: [:index, :show, :edit, :update]

  resources :topics do
    resources :comments

    collection do
      post :confirm
    end
  end

  resources :relationships, only: [:create, :destroy]

  resources :conversations do
    resources :messages
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :topic
  belongs_to :user
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_comment, only: [:destroy]
  #after_action :sending_pusher, only: [:create]

  # コメントを保存、投稿するためのアクション
  def create
    # ログインユーザーに紐付けてインスタンス生成するためbuildメソッドを私用する。
    @comment = current_user.comments.build(comment_params)
    @topic = @comment.topic
    #@notification = @comment.notifications.build(recipient_id: @topic.user_id, sender_id: current_user.id)
    # クライアント要求に応じてフォーマットを変更
    respond_to do |format|
      if @comment.save
        format.html { redirect_to topic_path(@topic), notice: 'コメントを投稿しました。'}
        format.json { render :show, status: :created, location: @comment }
        # JS形式でレスポンスを返す
        format.js { render :index }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    # クライアント要求に応じてフォーマットを変更
    respond_to do |format|
      if @comment.destroy
        format.html { redirect_to topic_path(@topic), notice: 'コメントを削除しました。'}
        format.json { render :show, status: :deletd, location: @comment }
        # JS形式でレスポンスを返す
        format.js { render :index }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    def comment_params
      params.require(:comment).permit(:topic_id, :user_id, :content)
    end

    def set_comment
      @comment = Comment.find(params[:id])
      @topic = @comment.topic
    end

    def sending_pusher
      Notification.sending_pusher(@notification.recipient_id)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<%= form_for([topic, comment], remote: true) do |f| %>
    <%= f.hidden_field :topic_id %>
    <div class="field">
        <%= f.text_field :content, placeholder: "内容", class: "form-control" %>
    </div>
    <div class="actions">
        <%= f.submit 'コメント送信', class: "btn btn-info" %>
    </div>
<% end %>

app/views/comments/_index.html.erb
<ul>
    <% comments.each do |comment| %>
        <% unless comment.id.nil? %>
            <li>
                <p class="left"><%= comment.user.name %>さんがコメントしました。</p>
                <p class="left"><%= comment.content %></p>
                <% if current_user.id == comment.user.id %>
                    <p class="right">
                        <%= link_to '', topic_comment_path(topic, comment), class: "fa fa-trash-o fa-lg", method: :delete, remote: true, data: { confirm: '本当に削除してよろしいですか？' } %>
                    </p>
                <% end %>
            </li>
        <% end %>
    <% end %>
</ul>

app/views/comments/index.js.erb
$("#comments_area").html("<%= j(render 'comments/index', { comments: @comment.topic.comments, topic: @comment.topic }) %>")
$(':text').val('')