config/routes.rb
Rails.application.routes.draw do

  root 'topics#index'

  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  resources :users, only: [:index, :show, :edit, :update]

  resources :topics do
    resources :comments

    collection do
      post :confirm
    end
  end

  resources :relationships, only: [:create, :destroy]

  resources :conversations do
    resources :messages
  end

end

app/models/topic.rb
class Topic < ActiveRecord::Base
  validates :content, presence: true
  belongs_to :user
  has_many :comments, dependent: :destroy
  mount_uploader :image, ImageUploader
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_topic, only: [:edit, :update, :destroy, :show]
  before_action :permit_user, only: [:destroy, :update]

  def index
    @topics = Topic.all.order(updated_at: :desc)
  end

  # showアクションを定義します。入力フォームと一覧を表示するためインスタンスを２つ生成します。
  def show
    @comment = @topic.comments.build
    @comments = @topic.comments
  end

  def new
    if params[:back]
      @topic = Topic.new(topics_params)
    else
      @topic = Topic.new
    end
  end

  def create
    @topic = Topic.new(topics_params)
    @topic.user_id = current_user.id
    if @topic.save
      flash[:success] = "ブログを作成しました！"
      redirect_to topics_path
      #NoticeMailer.sendmail_topic(@topic).deliver
    else
      render action: 'new'
    end
  end

  def edit
  end

  def update
    @topic.update(topics_params)
    if @topic.invalid?
      render action: 'edit'
    else
      flash[:success] = "トピックを更新しました！"
      redirect_to topics_path
    end
  end

  def destroy
    @topic.destroy
    flash[:success] = "トピックを削除しました！"
    redirect_to topics_path
  end

  def confirm
    @topic = Topic.new(topics_params)
    render 'new' if @topic.invalid?
  end

  private
    def topics_params
      params.require(:topic).permit(:content, :image, :image_cache)
    end

    def set_topic
      @topic = Topic.find(params[:id])
    end

    def permit_user
      redirect_to topics_path unless current_user.id == @topic.user.id || current_user.admin?
    end
end

app/helpers/topics_helper.rb
module TopicsHelper
  def topic_img(topic)
    if topic.image?
      img_url = topic.image
    end
    image_tag(img_url)
  end
end

app/views/topics/_form.html.erb
<%= form_for(@topic) do |f| %>
    <%= f.error_messages! %>
    <%= topic_img(@topic) if topic_img(@topic) %>
    <%= f.file_field :image, class: 'btn btn-info btn-block' %>
    <br>
    <%= f.label :content %>
    <%= f.text_area :content, size: "50x5", class: 'form-control', placeholder: :content %>
    <br>
    <%= f.submit '投稿', class: 'btn btn-primary btn-block' %>
<% end %>

app/views/topics/edit.html.erb
<div class="topic-wrapper">
    <h2>トピックを編集する</h2>
    <%= render 'form' %>
</div>

app/views/topics/index.html.erb
<h1>Topics一覧</h1>
<%= link_to 'トピックを作成する', new_topic_path, class: 'btn btn-default' %>
<%= link_to "もどる", :back, class: 'btn btn-primary btn-sm' %>
<br> <br>
<div class="topic-wrapper">
    <% @topics.each do |topic| %>
        <% if isfriend?(topic.user) %>
            <div class="row topic-row">
                <div class="topic-avatar">
                    <%= profile_img(topic.user) if profile_img(topic.user) %>
                </div>
                <p><%= link_to "#{topic.user.name}", user_path(topic.user) %></p>
                <p><%= topic.created_at.to_s(:human) %></p>
                <div class="clear-both"></div>
                <div class="topic-content">
                <p><%= simple_format(topic.content) %></p>
                </div>
                <div class="topic-img">
                    <%= topic_img(topic) if topic_img(topic) %>
                </div>
                <div class="topic_user_name">
                    投稿日: <%= localize(topic.created_at, format: :default) %><br>
                    <% if topic.created_at < topic.updated_at %>
                        (最終更新日: <%= localize(topic.updated_at, format: :default) %>)<br>
                    <% end %>
                </div>
                <br>
                <% if topic.comments.count >= 1 %>
                    <div class="topic_user_name"><strong>コメント<%= topic.comments.count %>件</strong></div>
                <% end %>
                <div class="topic_user_name"><%= link_to "コメントする", topic_path(topic) %></div>
                <% if current_user.id == topic.user.id %>
                    <%= link_to "編集", edit_topic_path(topic.id), class: 'btn btn-default btn-success' %>
                    <%= link_to "削除", topic_path(topic.id), method: :delete, data: { confirm: '本当によろしいですか？'}, class: 'btn btn-default btn-sm btn btn-danger' %>
                <% end %>
            </div>
        <% end %>
    <% end %>
</div>

app/views/topics/new.html.erb
<div class="topic-wrapper">
    <h2>トピックを作成する</h2>
    <%= render 'form' %>
</div>

app/views/topics/show.html.erb
<p id="notice"><%= notice %></p>
<div class="child row">
    <div class="topic-wrapper">
        <div class="topic-text">
            <p class="left"><strong>内容</strong></p>
            <p class="left"><%= @topic.content %></p>
            <div class="topic-img">
                <%= topic_img(@topic) if topic_img(@topic) %>
            </div>
            <p class="right">
            投稿者: <%= link_to "#{@topic.user.name}", user_path(@topic.user) %><br>
            作成時間: <%= localize(@topic.created_at, format: :default) %>
            </p>
        </div>
        <p>コメント一覧</p>
        <div id="comments_area" >
            <%= render 'comments/index', comments: @comments, topic: @topic %>
        </div>
        <%= render 'comments/form', comment: @comment, topic: @topic %>
        <% if current_user.id == @topic.user_id %>
            <%= link_to '編集', edit_topic_path(@topic) %> |
        <% end %>
        <%= link_to '戻る', topics_path %>
    </div>
</div>