config/routes.rb
Rails.application.routes.draw do

  root 'topics#index'

  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  resources :users, only: [:index, :show, :edit, :update]

  resources :topics do
    resources :comments

    collection do
      post :confirm
    end
  end

  resources :relationships, only: [:create, :destroy]

  resources :conversations do
    resources :messages
  end

end

app/views/layouts/_footer.html.erb
<div class="right-wrapper col-md-3 col-sm-3">
    <div class="topic-row">
        <p>Add1</p>
        <br>
        <br>
        <br>
        <br>
        <p>Add2</p>
        <br>
        <br>
        <br>
        <br>
    </div>
        <footer>
            プライバシー・規約・広告・AdChoices・Cookie・その他
            <p>faocmock © 2016</p>
        </footer>
</div>

app/views/layouts/_header.html.erb
<header>
    <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <%= link_to root_path, class: "navbar-brand" do %>
                    <i class="fa fa-facebook"></i>
                <% end %>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <%= link_to "#{user_path(current_user) if (user_signed_in? && current_user.name.present?)}" do %>
                            <span class="header-avatar"><%= profile_img(current_user) if profile_img(current_user) %></span><%= current_user.name %>
                    <% end %>
                    </li>
                    <li><%= link_to "ホーム", topics_path %></li>
                    <li>
                        <%= link_to users_path do %>
                            <i class="fa fa-users" aria-hidden="true"></i>
                        <% end %>
                    </li>
                    <li>
                        <%= link_to conversations_path do %>
                            <i class="fa fa-comments-o" aria-hidden="true"></i>
                        <% end %>
                    </li>
                    <% if user_signed_in? %>
                        <script>
                            var pusher = new Pusher('<%= Pusher.key %>');
                            var channel = pusher.subscribe('notifications'+<%= current_user.id.to_s %>);
                            channel.bind('message', function(data) {
                                $('#unreadcount').html(data.unread_count);
                            });
                        </script>
                    <% end %>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li role="separator" class="divider"></li>
                            <li><%= link_to "マイベージ", user_path(current_user) %></li>
                            <li><%= link_to "アカウント編集", edit_user_registration_path %></li>
                            <li role="separator" class="divider"></li>
                            <% if user_signed_in? %>
                                <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
                            <% end %>
                        </ul>
                    </li>
                </ul>
            </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
    </nav>
</header>

app/views/layouts/_nologin_header.html.erb
<header>
    <nav class="navbar2 navbar2-default navbar-fixed-top">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar2-header">
                <%= link_to root_path, class: "navbar2-brand" do %>
                    <i class="fa fa-facebook"></i> Faoemock
                <% end %>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar2-collapse" id="bs-example-navbar2-collapse-1">
                <ul class="nav navbar2-nav navbar2-right">
                    <li><%= link_to "#{current_user.name} さん", user_path(current_user) if user_signed_in? && current_user.name.present? %></li>
                    <li><%= link_to "ホーム", topics_path %></li>
                    <% if user_signed_in? %>
                        <script>
                            var pusher = new Pusher('<%= Pusher.key %>');
                            var channel = pusher.subscribe('notifications'+<%= current_user.id.to_s %>);
                            channel.bind('message', function(data) {
                                $('#unreadcount').html(data.unread_count);
                            });
                        </script>

                    <% end %>
                </ul>
            </div><!-- /.navbar2-collapse -->
        </div><!-- /.container-fluid -->
    </nav>
</header>

app/views/layouts/_sidebar.html.erb
<div class="left-wrapper col-md-2 col-sm-2">
    <p><%= link_to current_user.name, user_path(current_user) %></p>
    <p><%= link_to "アカウントを編集", edit_user_registration_path %></p>
    <p>content1</p>
    <p>content2</p>
    <br>
    <br>
    <br>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
    <meta charset="UTF-8">
    <head>
        <title>Faoemock</title>
        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
        <script src="https://js.pusher.com/3.1/pusher.min.js"></script>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <%= csrf_meta_tags %>
    </head>
    <body>
        <% if user_signed_in? %>
            <%= render 'layouts/header' %>
        <% else %>
            <%= render 'layouts/nologin_header' %>
        <% end %>

        <% flash.each do |type, msg| %>
            <% if type == 'notice' %>
                <div class="alert alert-success" role="alert"><%= msg %></div>
            <% elsif type == 'alert' %>
                <div class="alert alert-danger" role="alert"><%= msg %></div>
            <% else %>
                <div class="alert alert-<%= type %>" role="alert"><%= msg %></div>
            <% end %>
        <% end %>

        <% if user_signed_in? %>
        <div class="container">
            <%= render 'layouts/sidebar' %>
            <div class="wrapper col-md-6 col-sm-8">
                <%= yield %>
            </div>
            <%= render 'layouts/footer' %>
        </div>
        <% else %>
            <%= yield %>
        <% end %>

    </body>
</html>